### ISSUE TITLE
no way to see actual input?

### ISSUE THREAD

**Issue by stevesmoot** [aichaos/rivescript-go#11]
There doesn't seem to be any way to get at the un-simplified input
e.g., input of 
Jenny's place -> Jennys place
in a <call>function <star></call>
would like to be able to see Jenny's place not Jennys place
Did I miss it somehow?
also fine to get the whole input not just the <star> if that's available

**Comment by kirsle** [comment]
Some people have worked around this problem by utilizing the `SetUservar()` function from their app's code, e.g.

```go
bot.SetUservar(username, "origMsg", message)
reply := bot.Reply(username, message)
```

And then you can use `rs.GetUservar(username, "origMsg")` to retrieve it.

Let me know if this doesn't work; it *should* work but I don't think anyone's done it on the Go version yet.

**Comment by stevesmoot** [comment]
Clever.

Yes it works in go.
For clarity (& future users)
the use is

msg, err := rs.GetUservar(rs.CurrentUser(), "origMsg")

b/c you dont have username in the callback.

thanks!

-s
