### ISSUE TITLE
Unformatted Input

### ISSUE THREAD

**Issue by meowgorithm** [aichaos/rivescript-go#34]
I’m curious if it's possible to capture raw (or at least, unlowercased) input in a macro. I'm encountering a case where I need to capture case-sensitive input with punctuation and, as far as I can tell, the data would currently need to be captured outside of RiveScript.

**Comment by kirsle** [comment]
You can use SetUservar to set their raw message before calling Reply. You
can get it back in an object macro via `rs.GetUservar(rs.CurrentUser(),
"rawMsg")` or so.

**Comment by meowgorithm** [comment]
Brilliant, that totally makes sense. Thank you!
