### ISSUE TITLE
Topic Timeout

### ISSUE THREAD

**Issue by rmasci** [aichaos/rivescript-go#42]
I have a chatbot running, and I have programming that allows a user to start a troubleshooting session, and each step is a topic. The problem is they may go away, and then come back hours later and try to ask the chatbot another question -- but they're stuck inside the topic they left on which may be a few days ago. Is there a way to time out a topic? So that ten minutes later it goes back to topic=random?

**Comment by kirsle** [comment]
Hi,

There isn't a built-in feature for this but here's a couple ideas:

### Use a goroutine in the background to handle the timeout

* In your bot's reply-getting function you could `SetUservar` and store the timestamp of the user's last interaction.
* In the background goroutine, periodically pull `GetAllUservars()` and check users whose last contact time was older than a certain threshhold.
* `ClearUservars()` for each of those users.

Something like,

```go
go func() {
    for {
        time.Sleep(5 * time.Minute)
        users := bot.GetAllUservars()
        for _, username := range users {
            if timestamp, err := bot.GetUservar(username, "lastSeen"); err == nil {
                ts, _ := time.Parse(time.RFC3339, timestamp) // like "2006-01-02T15:04:05Z"
                if time.Now().Sub(ts) > (30 * time.Minute) {
                    // user has expired
                    bot.ClearUservars(username)
                }
            }
        }
    }
}()

// ...

func GetReply(username, message string) (string, error) {
    reply, err := bot.Reply(username, message)
    bot.SetUservar(username, "lastSeen", time.Now().Format(time.RFC3339)
    return reply, err
}
```

### Using Redis: add this feature to rivescript-go/sessions/redis and send a PR

Auto-expiring data is something Redis is really good at, and there's already a Redis-backed session driver for user variable storage, _but_ it doesn't have a feature to do this yet. If you're up for it, you could add this feature to the Redis session driver and send me a pull request (assuming you'd want to use Redis at all for your bot).

That change might look like:

* [In the Config struct here](https://github.com/aichaos/rivescript-go/blob/aa903a726d956217b7e62f1843317bc1d27b9de2/sessions/redis/extra.go#L82), add a key like "AutoExpire time.Duration" to let the user configure a time at which to expire the Redis keys automatically (default zero-value meaning "don't expire")
* [When it calls Set() on the Redis client](https://github.com/aichaos/rivescript-go/blob/aa903a726d956217b7e62f1843317bc1d27b9de2/sessions/redis/extra.go#L82), replace the 0 for the timeout value with the AutoExpire duration from the config.
