### ISSUE TITLE
Javascript nonfunctional?

### ISSUE THREAD

**Issue by jerrimus** [aichaos/rivescript-go#46]
Tried with compiled and self-compiled versions.

Using examples from https://pkg.go.dev/github.com/aichaos/rivescript-go/lang/javascript   any time I try to execute any javascript, I just get my reply for unknown question.

I got the pre-compiled from the releases page, just pulled and built the cmd directory here. Am I compiling it the wrong way?

**Comment by kirsle** [comment]
Here is a complete example where JavaScript works:

```go
package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/aichaos/rivescript-go"
	"github.com/aichaos/rivescript-go/lang/javascript"
)

func main() {
	bot := rivescript.New(&rivescript.Config{Debug: true})
	jsHandler := javascript.New(bot)
	bot.SetHandler("javascript", jsHandler)

	bot.Stream(`
	> object add javascript
		var a = args[0];
		var b = args[1];
		return parseInt(a) + parseInt(b);
	< object

	> object setvar javascript
		// Set the user's name via JavaScript
		var uid = rs.CurrentUser();
		rs.SetUservar(args[0], args[1], args[2]);
	< object

	+ add # and #
	- <star1> + <star2> = <call>add <star1> <star2></call>

	+ my name is *
	- I will remember that.<call>setvar <id> name <formal></call>

	+ what is my name
	- You are <get name>.
	`)
	bot.SortReplies()

	// Drop into the interactive command shell.
	reader := bufio.NewReader(os.Stdin)
	for {
		fmt.Print("You>")
		text, _ := reader.ReadString('\n')
		text = strings.TrimSpace(text)
		if len(text) == 0 {
			continue
		}

		reply, err := bot.Reply("localuser", text)
		if err != nil {
			fmt.Print("Error>", err.Error(), "\n")
		} else {
			fmt.Print("RiveScript>", reply, "\n")
		}
	}
}
```

Some notes I found:

* The example on the Go doc looked slightly broken in practice: in the setname function where it got rs.CurrentUser() and passed that in to SetUservar(), it seems (for some reason?) that CurrentUser() !== args[0] though they both looked like the same string to me when printed.
* Also note, currently this uses [robertkrimen/otto](https://github.com/robertkrimen/otto) for the JS engine which is mostly ES5 syntax only (and it's possible to break it even with ES5 syntax). I'd like to replace it with [https://github.com/dop251/goja](dop251/goja) which brings ES6 syntax and is harder to break. A pull request to convert it would be welcomed! I had good experiences with goja when I switched Otto over to it in [my videogame project](https://github.com/SketchyMaze/doodle/commit/4d08bf1d8513f76d9b9e2bde22a86c7c7d4fd6d6#diff-7de98cb8d3d7e48c085b801faf2966ee8eda53b652b3ee583630a8ad7a6956b7) - the API between otto/goja is quite similar, I just haven't gotten around to updating rivescript-go in quite some time!
