### ISSUE TITLE
Session Management in RiveScript-go

### ISSUE THREAD

**Issue by raviteja-ms** [aichaos/rivescript-go#8]
Is there any functionality in rivescript-go library to plugin a session manager as in rivescript-python library as this example: https://github.com/aichaos/rivescript-python/tree/master/eg/sessions

If not Please suggest me a method to **persistently** store the session and chat contexts/history.

**Comment by kirsle** [comment]
It's on the to-do list. Python didn't get that feature until somewhat recently itself.

In the mean time, there's `GetUservars()` and `SetUservars()` so you can export vars, save them to whatever persistent storage you want, and later get them back and put them back into the RiveScript instance. [Here's an example](https://github.com/aichaos/rivescript-js/tree/master/eg/persistence) (JavaScript), but the logic could be the same: before getting a reply, check if the user has any vars, if not grab them from storage and set them. After the reply, export them all back to storage.

**Comment by raviteja-ms** [comment]
Okay...!! Thanks for your suggestion. :+1:
